name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v1
      with:
        resource-group: aks-rg
        cluster-name: shahinAksCluster

    - name: Deploy to AKS
      uses: Azure/k8s-deploy@v4
      with:
        manifests: |
          manifests/nginx-deployment.yaml
